name: Test macos workflow

on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin-test-macos:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install vfox (MacOS)
        run: |
          brew tap version-fox/tap
          brew install vfox

      - name: Generate PHP plugin
        run: |
          zip -r php.zip ./

      - name: Install packages
        run: brew install autoconf automake bison freetype gd gettext icu4c krb5 libedit libiconv libjpeg libpng libxml2 libzip pkg-config re2c zlib

      - name: Test
        shell: bash
        run: |
          vfox add -s php.zip
          vfox install php@latest
          vfox use -p php@$(vfox list php | sed -n 's/-> v//p')
          eval "$(vfox activate bash)"
          php -v
          php -m
          composer -V
