name: Test workflow

on:
  pull_request:
  # push:
  schedule:
    - cron: 0 0 * * 5

jobs:
  plugin-test-linux:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ ubuntu-20.04, macos-13, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install vfox (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
          sudo apt-get update
          sudo apt-get install vfox
          echo 'eval "$(vfox activate bash)"' >> ~/.bashrc

      - name: install vfox (MacOS)
        if: runner.os == 'MacOS'
        run: |
          brew tap version-fox/tap
          brew install vfox
          echo 'eval "$(vfox activate bash)"' >> ~/.bashrc
          echo 'eval "$(vfox activate zsh)"' >> ~/.zshrc

      - name: install vfox (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          scoop install vfox

      - name: View vfox version
        run: |
          vfox -v

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate PHP plugin
        if: runner.os != 'Windows'
        run: |
          zip -r php.zip ./
      - name: Generate PHP plugin
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path .\* -DestinationPath .\php.zip

      - name: Install packages
        if: runner.os == 'Linux'
        run: sudo apt-get install -y curl autoconf build-essential locate libgd-dev libjpeg-dev libpng-dev libonig-dev libzip-dev libxml2-dev libssl-dev libsqlite3-dev libcurl4-openssl-dev libreadline-dev
      - name: Install packages
        if: runner.os == 'MacOS'
        run: brew install autoconf automake bison freetype gd gettext icu4c krb5 libedit libiconv libjpeg libpng libxml2 libzip pkg-config re2c zlib

      - name: Add PHP And Install Runtime
        run: |
          vfox add -s php.zip
          vfox install php@8.3.3

      #     php -v
      #     php -m
      #     composer -V

      - name: Test
        if: runner.os != 'Windows'
        run: |
          vfox use php@8.3.3
          php -v
          php -m
          composer -V
      - name: Test
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          vfox use -p php@8.3.3
          Invoke-Expression "$(vfox activate pwsh)"
          php -v
          php -m
          composer -V
          
          
